import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const source=readFileSync(new URL('../public/modules/cloud.mjs',import.meta.url),'utf8').replace(/^import .*\n/,'').replace(/export /g,'');
async function page(signedIn,athleteFailure=false){const dom=new JSDOM(html,{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;w.flushQueue=async q=>q;w.fetch=async path=>{let status=200,body={};if(path==='/api/auth/config')body={google:true,email:true};if(path==='/api/me'){status=signedIn?200:401;body=signedIn?{id:'u',email:'az@example.test',earlyAccess:false}:{error:'Authentication required'};}if(path==='/api/athletes'){status=athleteFailure?503:200;body=athleteFailure?{error:'Athletes unavailable'}:{athletes:[]};}if(path.startsWith('/api/races'))body={races:[]};return {ok:status===200,status,json:async()=>body};};w.eval(source+'\nstartCloud({getAthleteId:()=>null,getHistory:()=>[],setHistory:()=>{},onSave:()=>{},onDelete:()=>{},save:()=>{},selectAthlete:()=>{}})');await new Promise(r=>setTimeout(r,20));return dom;}
test('Google session replaces sign-in form and displays account identity',async()=>{const d=await page(true),doc=d.window.document;assert.equal(doc.getElementById('signedOut').hidden,true);assert.equal(doc.getElementById('signedIn').hidden,false);assert.equal(doc.getElementById('accountSummary').textContent,'Signed in');assert.equal(doc.getElementById('headerAccountEmail').textContent,'az@example.test');assert.equal(doc.getElementById('headerLogout').hidden,false);assert.equal(doc.getElementById('accountMenu').open,false);d.window.close();});
test('athlete failure does not hide a valid signed-in account',async()=>{const d=await page(true,true);assert.equal(d.window.document.getElementById('signedOut').hidden,true);assert.equal(d.window.document.getElementById('signedIn').hidden,false);d.window.close();});
test('signed-out user can choose distinct email registration and login modes',async()=>{const d=await page(false),doc=d.window.document;assert.equal(doc.getElementById('signedOut').hidden,false);assert.equal(doc.getElementById('googleLogin').hidden,false);doc.getElementById('chooseRegister').click();assert.equal(doc.getElementById('loginButton').hidden,true);assert.equal(doc.getElementById('authPassword').autocomplete,'new-password');doc.getElementById('chooseLogin').click();assert.equal(doc.getElementById('registerButton').hidden,true);d.window.close();});
test('header account menu signs out through existing flow and retains device data',async()=>{const d=await page(true),w=d.window,doc=w.document;w.localStorage.setItem('racesplit-v3','saved-device-races');w.localStorage.setItem('racesplit-outbox:u','retained-pending-upload');const menu=doc.getElementById('accountMenu');menu.open=true;doc.getElementById('headerLogout').click();await new Promise(r=>setTimeout(r,20));assert.equal(doc.getElementById('accountSummary').textContent,'Sign in');assert.equal(doc.getElementById('headerLogout').hidden,true);assert.equal(menu.open,false);assert.equal(w.localStorage.getItem('racesplit-v3'),'saved-device-races');assert.equal(w.localStorage.getItem('racesplit-outbox:u'),'retained-pending-upload');menu.open=true;doc.getElementById('headerAccountLink').click();assert.equal(menu.open,false);assert.equal(doc.getElementById('headerAccountLink').getAttribute('href'),'#accountPanel');w.close();});
