import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const code=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('let state='));
function page(){const dom=new JSDOM(html,{url:'https://staging.example',runScripts:'outside-only'});dom.window.console.warn=()=>{};dom.window.requestAnimationFrame=()=>{};dom.window.alert=()=>{};dom.window.confirm=()=>true;return dom;}
const delay=()=>new Promise(resolve=>setTimeout(resolve,0));
test('timer starts and saves locally without account, network or IndexedDB',async()=>{const dom=page(),w=dom.window;w.eval(code);await delay();w.document.getElementById('mainBtn').click();w.document.getElementById('mainBtn').click();w.document.getElementById('saveRace').click();assert.equal(w.raceSplitBridge.getHistory().length,1);const keys=Object.keys(w.localStorage);const saved=keys.map(k=>JSON.parse(w.localStorage.getItem(k))).find(v=>v.history);assert.equal(saved.history.length,1);assert.ok(saved.start);assert.ok(!saved.history[0].ownerId);dom.window.close()});
test('active and paused timer survives reload with local state preserved',async()=>{const first=page();first.window.eval(code);await delay();first.window.document.getElementById('mainBtn').click();first.window.document.getElementById('pauseBtn').click();const k=Object.keys(first.window.localStorage)[0],raw=first.window.localStorage.getItem(k),before=JSON.parse(raw);const second=page();second.window.localStorage.setItem(k,raw);second.window.eval(code);await delay();const after=JSON.parse(second.window.localStorage.getItem(k));assert.equal(after.start,before.start);assert.equal(after.pausedAt,before.pausedAt);assert.equal(second.window.document.getElementById('status').textContent,'PAUSED');first.window.close();second.window.close()});
test('IndexedDB recovery precedes empty initial-state save',async()=>{const dom=page(),w=dom.window,record={raw:JSON.stringify({start:Date.now()-10000,ends:[5000],history:[],pausedMs:0,finished:false})};const writes=[];const database={objectStoreNames:{contains:()=>true},transaction(_store,mode){const tx={objectStore(){return {get(){const request={};queueMicrotask(()=>{request.result=record;request.onsuccess?.()});return request},put(value){writes.push(value);queueMicrotask(()=>tx.oncomplete?.());return {}}}}};return tx}};w.indexedDB={open(){const req={};queueMicrotask(()=>{req.result=database;req.onsuccess?.()});return req}};w.eval(code);await delay();assert.equal(JSON.parse(w.localStorage.getItem(Object.keys(w.localStorage)[0])).start,JSON.parse(record.raw).start);assert.ok(writes.every(v=>JSON.parse(v.raw).start));dom.window.close()});
